### PR TITLE
Move templates out of component files into template files

### PR DESCRIPTION
**Pull request by christine-w**
Long PR but just copying and pasting.

### CODE REVIEW

**Review by Blaradox — CHANGES_REQUESTED** [review]
Hey, for some reason there's a merge conflict on this file. I'm not sure why that would be the case. From what I can tell you just changed the file to use a templateURL... I might be missing something though

**Comment by christine-w** [comment]
Probably because this was not done off the karma branch. Should be quick to resolve. I'll look at it.

**Comment by christine-w** [comment]
OK, @Blaradox -- conflict resolved.

**Review by Blaradox — APPROVED** [review]

**Comment by Blaradox** [comment]
great, thanks!

**Pull request merged**
