### PR TITLE
Database branch3

### PR DESCRIPTION
**Pull request by dfried514**

### CODE REVIEW

**Review by christine-w — APPROVED** [review]
Reviewed this against schema documented in our App Plan.

**Review by christine-w — APPROVED** [review]
Let's merge this to start getting the persistence layer going. However, here are a few questions and things to consider for the rest of the DB methods:
- How are errors handled? 
- How will the calling program know whether this succeeded or failed? Should this return a promise?
- Looking at the addUser method, the method signature does not really abstract the table structure from the client system. This is a design question that we haven't really discussed but a more abstracted alternative is to accept an object and unpack and validate it in the DB helpers.

**Comment by dfried514** [comment]
Yes, pool.query returns  a Promise, which is unhandled currently.  I can certainly fix that to issue a message based on success or failure.

Also, how would you change the method signature to work with your server endpoint when you want to add a user to the system?

Also you need to do npm install pg --save to work with the 'pg' module.

**Comment by christine-w** [comment]
If pool.query returns a Promise, then returning that promise would be sufficient and the app server can handle messaging.

As for the interface provided by the DB helper functions, I don't know if there is an absolutely correct or incorrect way -- it's a design choice you can make. The server hasn't been using these DB methods yet so there is still a lot of flexibility there. The current pattern for the contract (used in the addUser method) is for the server to deconstruct whatever object (in the addUser case, a user object) into the respective properties in order to call the DB helper function. Since these properties pretty much map to the table columns, this essentially means the server now has some knowledge of the table structure. An alternative is for the DB helper functions to abstract this by accepting a single parameter that is the user object (vs four parameters) and then the DB helper function handles unpacking and throwing an error if needed data is missing. Just something for you to consider -- we can implement the server to suit either approach.

**Pull request merged**
